### ISSUE TITLE
뚝뚝 끊기는 영상 개선

### ISSUE THREAD

**Issue by jogiking** [boostcampwm-2021/iOS10-JipJung#172]
## 설명
부드럽지 않은 영상을 개선/삭제합니다
특히 샤워기 영상에서 피드백 받았습니다

![IMG_CE2B1D028EE6-1](https://user-images.githubusercontent.com/38206212/143521314-649ba121-7b25-48a3-a30b-b289ff13f6f7.jpeg)

**Comment by hyunsik-0h** [comment]
아카이브 v1.6 업데이트
